name: Enable auto-merge for Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  enable-auto-merge:
    if: |
      github.actor == 'dependabot[bot]'
    name: Enable Dependable Auto-Merge
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
